package main

import "fmt"

type AutoGenerated struct {
	Age   int    `json:"age"`
	Name  string `json:"name"`
	Child []int  `json:"child"`
}

func main() {

	v1:=1
	v2:=2
	defer func(v11 interface{}) {
		fmt.Println(v11)
		fmt.Println(v2)
	}(v1)

	v1 = 123
	v2=312




}