package main

import (
	"db_mirror/db"
	"fmt"
	"time"
)

type AutoGenerated struct {
	Age   int    `json:"age"`
	Name  string `json:"name"`
	Child []int  `json:"child"`
}

func main() {

	h := db.NewHandlerDb(6)

	t := time.Now()

	m, err := h.Engine.QueryString(`
SELECT
	concat( a.CORP, a.SKU_ID ) AS ID 
FROM
	 CACHE_JD_PRICE a 
WHERE
	a.UPDATE_TIME > to_date( '2020-12-15 12:12:12', 'yyyy-mm-dd hh24:mi:ss' ) 
 
`)
	if err != nil {
		fmt.Println(err)
	}

	fmt.Println(time.Since(t))
	fmt.Println(len(m))

	//fmt.Println(m)

}
